### ISSUE TITLE
java.lang.NullPointerException u metodi jpa.handlers.JpaTaskHandler.getChef()

### ISSUE THREAD

**Issue by marko921** [mgrumic/ProjectGuru#3]
Kod editovanja zadatka.

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at projectguru.jpa.handlers.JpaTaskHandler.getChef(JpaTaskHandler.java:591)
	at projectguru.jpa.handlers.JpaTaskHandler.checkTaskChefPrivileges(JpaTaskHandler.java:70)
	at projectguru.jpa.handlers.JpaTaskHandler.editSubtask(JpaTaskHandler.java:197)
	at projectguru.controllers.FormAddTaskController$4.handle(FormAddTaskController.java:177)

**Comment by kormang** [comment]
OK poradicu na tome

**Comment by kormang** [comment]
Ne znam kako da reprodukujem taj bug?
